sudo: required
language: node_js
env:
  - BUILD_ENV=ci
install:
  - npm i
cache: npm
node_js:
  - "node"
branches:
  only:
    - master
    - test
    - /^greenkeeper/.*$/
jobs:
  include:
  - stage: build
    script:
      - npm run build
      - npm run test
    after_success: npm run coverage


